# Change these first
owner: agentsphere # Your GitHub organization or username, where this repository lives
repo: up # The name of this repository

sites:
  - name: asp App Backend Service 
    url: https://agents.prod.agentsphere.cloud/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.agentsphere.cloud
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status AgentSphere Services
  introTitle: "Status & Uptime for AgentSphere Services"
  introMessage: >
    This page provides the latest uptime information and real-time monitoring data 
    for all **Agentsphere** services. Our goal is to ensure transparency and keep 
    you informed about service availability and any incidents as they happen.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Support
      href: https://agentsphere.atlassian.net/servicedesk/customer/portal/1

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
